# Generated by Django 3.2.23 on 2023-11-26 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='rated_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
