# Generated by Django 3.2.23 on 2023-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20231203_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
