# Generated by Django 3.2.23 on 2023-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_recipe_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sum_of_rating',
            field=models.FloatField(default=0),
        ),
    ]
