# Generated by Django 3.2.23 on 2023-12-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_recipe_sum_of_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
    ]
